spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
server:
  port: 6001
  address: 127.0.0.1
logging:
  level:
    org.springframework.security: debug


